defaults: &defaults
  flow:
    initial: xlsx_to_csv
    xlsx_to_csv:
      extension: py
      input:
        - input
        - output
      output:
        output:
          extension: csv
          programs:
            - traces_filter
    traces_filter:
      extension: py
      input:
        - input
        - output
        - dates
        - polygon
        - first_column
        - last_column
      output:
        output:
          extension: csv
          programs:
            - stop_stats
        dates:
          extension: csv
          programs:
            - stop_stats
    stop_stats:
      extension: py
      input:
        - input
        - dates
        - existing
        - non_existing
        - output
      output:
        output:
          extension: xlsx
          programs:
            - process_stops
        existing:
          extension: csv
          programs:
            - process_stops
        non_existing:
          extension: csv
          programs:
            - process_stops
    process_stops:
      extension: py
      input:
        - input
        - existing
        - non_existing
        - output
      output:
        output:
          extension: csv
          programs:
            - stop_centroids
    stop_centroids:
      extension: py
      input:
        - input
        - std_and_mean
        - frequencies
        - centroids
      output:
        centroids:
          extension: csv
          programs:
             - distance_matrices
    distance_matrices:
      extension: py
      input:
        - centroids
        - output
        - polygon
        - clients
        - distance_stops_to_stops
        - time_stops_to_stops
        - distance_stops_to_customers
        - time_stops_to_customers
      output:
        output:
          extension: csv
          programs:
        distance_stops_to_stops:
          extension: csv
          programs:
        time_stops_to_stops:
          extension: csv
          programs:
        distance_stops_to_customers:
          extension: csv
          programs:
        time_stops_to_customers:
          extension: csv
          programs:
    flm:
      extension: py
      input:
        - centroids
        - output
        - polygon
        - clients
        - distance_stops_to_stops
        - time_stops_to_stops
        - distance_stops_to_customers
        - time_stops_to_customers
      output:
        output:
          extension: csv
          programs:
        distance_stops_to_stops:
          extension: csv
          programs:
        time_stops_to_stops:
          extension: csv
          programs:
        distance_stops_to_customers:
          extension: csv
          programs:
        time_stops_to_customers:
          extension: csv
          programs:
    upload:
      input:
        - input
      output:
        frequencies:
          extension: csv
          programs:
  arguments:
    output: input
  sticky_arguments:
    - std_and_mean
    - centroids

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults