defaults: &defaults
  flow:
    initial: xlsx_to_csv
    xlsx_to_csv:
      extension: py
      input:
        - input
        - output
      output:
        output:
          extension: csv
          programs:
            - gps_stats
    gps_stats:
      extension: py
      input:
        - input
        - output
        - polygon
        - co2
        - capacity
        - first_column
        - last_column
        - fuel
        - stats
        - traces
      output:
        traces:
          extension: csv
          programs:
            - upload
        stats:
          extension: csv
          programs:
            - upload
    upload:
      input:
        - traces
        - stats
      output:
  arguments:
    output: input
  upload_arguments:
    traces: traces_name
    stats: stats_name

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults